apiVersion: apps/v1
kind: Deployment
metadata:
  name: jihye-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jihye-springboot
  template:
    metadata:
      labels:
        app: jihye-springboot
    spec:
      containers:
        - name: springboot
          image: jihye0906/jihye-docker-demo:jihye-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jihye-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jihye-springboot
